[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.basedpyright]
typeCheckingMode = "standard"

[tool.ruff]
[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "ANN",
    "S",
    "B",
    "A",
    "C4",
    "EM",
    "ISC",
    "ICN",
    "INP",
    "PIE",
    "PYI",
    "Q",
    "RSE",
    "RET",
    "SIM",
    "TCH",
    "PTH",
    "ARG",
    "PD",
    "PL",
    "NPY",
    "PERF",
    "RUF",
]
ignore = [
    "E501",  # Line too long
    "S101",  # Use of assert
    "PD008", # Pands loc vs at
]
